spring.application.name=monitoramento-entregas-api

spring.datasource.url=jdbc:h2:mem:entregas_api
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.format-sql=true

#Comando para a jpa criar a tabela e tbm atualizar ela automaticamente
spring.jpa.hibernate.ddl-auto=update
